### ISSUE TITLE
Self Account Info

### ISSUE THREAD

**Issue by Helcostr** [Sidemen19/mediawiki.js#3]
Should we store the account info in the bot itself? Updated upon login?

Can be done here:
https://github.com/Sidemen19/mediawiki.js/blob/645fae1695eb8bbd13bf0c20991cdfceec6777a5/src/index.js#L51

Or here:
https://github.com/Sidemen19/mediawiki.js/blob/645fae1695eb8bbd13bf0c20991cdfceec6777a5/src/index.js#L510

**Comment by Sidemen19** [comment]
Yeah, I'll make it so that upon initialisation of the bot it makes a request and caches the data for any further usage.
